#!/bin/bash
set -ex

# Set the base URL of the YakAPI server
base_url="http://localhost:8080"

# Function to send a CI command
send_command() {
  local command="$1"
  curl -X POST -H "Content-Type: application/json" -d "{\"command\":\"$command\"}" "$base_url/v1/ci"
  echo
}

send_command "$@"