#!/bin/bash
set -e

# Set the base URL of the YakAPI server
base_url="${YAKAPI_SERVER:-http://localhost:8080}"

# Function to send a CI command
send_command() {
  local command="$1"
  curl -X POST -H "Content-Type: application/json" -d "{\"command\":\"$command\"}" "$base_url/v1/ci?wait=1"
  echo
}

send_command "$@"
