#!/bin/bash
set -e

echo "==> Building"
GOOS=linux GOARCH=arm GOARM=7 go build -o bin/yakapi-arm .

echo "==> Deploying"
target="/data/yakapi/yakapi.$(date +%Y%m%d%H%M%S)"
scp ./bin/yakapi-arm deploy@bni:$target
ssh deploy@bni "chmod +x $target && ln -sf $target /data/yakapi/yakapi.current && sudo systemctl restart yakapi"
