---
name: deploy-yak-prime
run-name: deploying to yak-prime
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: yak-prime
    concurrency: yak-prime
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.23.0'
    - run: go build -o bin/yakapi.${{ github.sha }} .
    - run: scp -o 'StrictHostKeyChecking no' bin/* deploy@yak-prime:/data/yakapi
    - run: ssh deploy@yak-prime "chmod +x /data/yakapi/yakapi.${{ github.sha }} && ln -sf /data/yakapi/yakapi.${{ github.sha }} /data/yakapi/yakapi.current && sudo /bin/systemctl restart yakapi"
    - run: curl -v http://yak-prime/v1
